p1:
	gcc -g -W -Wall 5_1.c -o 1
p2:
	gcc -g -W -Wall 5_2.c -o 2
p3:
	gcc -g -W -Wall 5_3.c -o 3
p4:
	gcc -g -W -Wall 5_4.c -o 4
p5:
	gcc -g -W -Wall 5_5.c -o 5
p6:
	gcc -g -W -Wall 5_6.c -o 6
p7:
	gcc -g -W -Wall 5_7.c -o 7
p8:
	gcc -g -W -Wall 5_8.c -o 8
p9:
	gcc -g -W -Wall 5_9.c -o 9
p10:
	gcc -g -W -Wall 5_10.c -o 10
p11:
	gcc -g -W -Wall 5_11.c -o 11
all: p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11
clean:
	rm 1 2 3 4 5 6 7 8 9 10 11
