p1:
	gcc -W -Wall 3_1.c -o 1
p2:
	gcc -W -Wall 3_2.c -o 2
p3:
	gcc -W -Wall 3_3.c -o 3
p4:
	gcc -W -Wall 3_4.c -o 4
p5:
	gcc -W -Wall 3_5.c -o 5
p6:
	gcc -W -Wall 3_6.c -o 6
p7:
	gcc -W -Wall 3_7.c -o 7
p8:
	gcc -W -Wall 3_8.c -o 8
p9:
	gcc -W -Wall 3_9.c -o 9
p10:
	gcc -W -Wall 3_10.c -o 10
p11:
	gcc -W -Wall 3_11.c -o 11
all: p1 p2 p3 p4 p5 p6 p7 p8 p9 p10 p11
clean:
	rm 1 2 3 4 5 6 7 8 9 10 11
